# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='course',
        ),
    ]
